### ISSUE TITLE
Lizenz festlegen und dokumentieren

### ISSUE THREAD

**Issue by cdeschryver** [TUK-EIT/tukpod#2]
Datei LICENSE anlegen mit Lizenzinformationen

**Comment by cdeschryver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lizenz Code EIT festlegen und in GitHub dokumentieren](https://trello.com/c/fbBy0r48/37-lizenz-code-eit-festlegen-und-in-github-dokumentieren)

**Comment by janiskrieger** [comment]
added the GNU General Public License v3.0
